---
name: ansible tests

on: # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distribution:
          - dist: centos
            version: 9-Stream
          - dist: almalinux
            version: "10"
          - dist: rockylinux
            version: "9"
          - dist: rockylinux
            version: "10"

    steps:
      - uses: actions/checkout@v6

      - name: install dependencies
        run: >
          pip3 install
          ansible
          ansible-lint
          yamllint

      - name: create lxc container
        uses: lkiesow/setup-lxc-container@v1
        with:
          dist: ${{ matrix.distribution.dist }}
          release: ${{ matrix.distribution.version }}
          name: test

      - name: yamllint
        run: |
          yamllint .

      - name: ansible-lint
        run: |
          ansible-lint

      - name: create role structure for tests
        working-directory: .github
        run: |
          mkdir -p roles
          ln -s .. roles/dnf_autoupdate

      - name: test deployment
        working-directory: .github
        run: |
          ansible-playbook -i test, deploy.yml
